eShopVite/config/routes.rb
EShopVite::Application.routes.draw do

  resources :itemfriends

  root :to => "itemservices#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
     get "sign_in", :to => "devise/sessions#new"
     get "/", :to => "devise/sessions#new"
     get "sign_out", :to => "devise/sessions#destroy"
     get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end



  resources :itemservices

   resources :itemservices do
       resources :itemfriends
   end

  match 'itemfriends/new/:itemservice_id'          => 'itemfriends#new'
 #  match 'itemfriends/new/:itemservice_id/:emailid' => 'itemfriends#new'

end

eShopVite/app/models/itemservice.rb
require 'digest/sha1'
class Itemservice < ActiveRecord::Base
  
  belongs_to :User
  has_many :Itemfriend 
 
 attr_accessible  :user_id, :itemfriend_attributes, :emailids, :emailmessage,  :amount, :begindate, :enddate, :friendslistid, :itemdescription, :quantity, :siteurl, :User
  
before_save :generate_token

def generate_token
  self.friendslistid = Digest::SHA1.hexdigest([Time.now, rand].join)

end



end

eShopVite/app/controllers/itemservices_controller.rb
class ItemservicesController < ApplicationController

before_filter :authenticate_user!

  # GET /itemservices
  # GET /itemservices.json
  def index
    if user_signed_in?
     @current_user = User.find(current_user.id) 
     @itemservices = @current_user.itemservices
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @itemservices }
    end
  end

  # GET /itemservices/1
  # GET /itemservices/1.json
  def show

   if user_signed_in?
      @itemservice = Itemservice.find(params[:id])
      @itemfriend = @itemservice.Itemfriend
   end 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @itemservice }
    end
  end

  # GET /itemservices/new
  # GET /itemservices/new.json
  def new

   @itemservice = Itemservice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @itemservice }
    end
  end

  # GET /itemservices/1/edit
  def edit
    @itemservice = Itemservice.find(params[:id])
  end

  # POST /itemservices
  # POST /itemservices.json
  def create

   @current_user = User.find(current_user.id)
   @itemservice = @current_user.itemservices.new(params[:itemservice])

    respond_to do |format|
     if @itemservice.save

        @emailids = @itemservice.emailids.split(';')
        @emailids.each do |emailx|
            MyMailer.shopping_invitation(@itemservice,emailx).deliver
       end

        format.html { redirect_to @itemservice, notice: 'Itemservice was successfully created.' }
        format.json { render json: @itemservice, status: :created, location: @itemservice }
      else
        format.html { render action: "new" }
        format.json { render json: @itemservice.errors, status: :unprocessable_entity }
      end
   end
  end

  # PUT /itemservices/1
  # PUT /itemservices/1.json
  def update
    @itemservice = Itemservice.find(params[:id])

    respond_to do |format|
      if @itemservice.update_attributes(params[:itemservice])
        format.html { redirect_to @itemservice, notice: 'Itemservice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @itemservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itemservices/1
  # DELETE /itemservices/1.json
  def destroy
    @itemservice = Itemservice.find(params[:id])
    @itemservice.destroy

    respond_to do |format|
      format.html { redirect_to itemservices_url }
      format.json { head :no_content }
    end
  end
end

eShopVite/app/helpers/itemservices_helper.rb
module ItemservicesHelper
end

eShopVite/app/views/itemservices/_form.html.erb
<%= form_for(@itemservice) do |f| %>
  <% if @itemservice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@itemservice.errors.count, "error") %> prohibited this itemservice from being saved:</h2>

      <ul>
      <% @itemservice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.hidden_field :user_id, :value => session[:user_id] %>
  <div class="field">
    <%= f.label :siteurl %>
    <%= f.text_field :siteurl %>
  </div>
  <div class="field">
    <%= f.label :itemdescription %><br />
    <%= f.text_area :itemdescription, :cols => 100, :rows => 5  %>
  </div>
  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :begindate %>
    <%= f.datetime_select :begindate %>
  </div>
  <div class="field">
    <%= f.label :enddate %>
    <%= f.datetime_select :enddate %>
  </div>

  <div class="field">
    <%= f.label :emailids %><br />
    <%= f.text_area :emailids, :cols => 100, :rows => 5 %>
  </div>

  <div class="field">
    <%= f.label :emailmessage %><br />
    <%= f.text_area :emailmessage,  :cols => 100, :rows => 10 %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

eShopVite/app/views/itemservices/edit.html.erb
<h1>Editing itemservice</h1>

<%= render 'form' %>

<%= link_to 'Show', @itemservice %> |
<%= link_to 'Back', itemservices_path %>

eShopVite/app/views/itemservices/index.html.erb
<h1>Listing itemservices</h1>

<table>
  <tr>
    <th>Siteurl</th>
    <th>Itemdescription</th>
    <th>Quantity</th>
    <th>Amount</th>
    <th>User</th>
  </tr>

<% @itemservices.each do |itemservice| %>
  <tr>
    <td><%= itemservice.siteurl %></td>
    <td><%= itemservice.itemdescription %></td>
    <td><%= itemservice.quantity %></td>
    <td><%= itemservice.amount %></td>
    <td><%= itemservice.User %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Itemservice', new_itemservice_path %>

eShopVite/app/views/itemservices/new.html.erb
<h2>New itemservice</h2>

<%= render 'form' %>

<%= link_to 'Back', itemservices_path %>

eShopVite/app/views/itemservices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Siteurl:</b>
  <%= @itemservice.siteurl %>
</p>

<p>
  <b>Itemdescription:</b>
  <%= @itemservice.itemdescription %>
</p>

<p>
  <b>Quantity:</b>
  <%= @itemservice.quantity %>
</p>

<p>
  <b>Amount:</b>
  <%= @itemservice.amount %>
</p>

<p>
  <b>Begindate:</b>
  <%= @itemservice.begindate %>
</p>

<p>
  <b>Enddate:</b>
  <%= @itemservice.enddate %>
</p>

<p>
  <b>EmailIds:</b>
  <%= @itemservice.emailids %>
</p>

<p>
  <b>Email Message:</b>
  <%= @itemservice.emailmessage %>
</p>
<table>
  <tr>
    <th>Interested</th>
    <th>Qty</th>
    <th>Amount</th>
    <th>Comments</th>
    <th>Itemservice</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @itemservice.Itemfriend.each do |itemfriend| %>
  <tr>
    
<td><%= if itemfriend.interested then  "Yes" else "No" end %></td>
    <td><%= itemfriend.qty %></td>
    <td><%= itemfriend.amount %></td>
    <td><%= itemfriend.comments %></td>
    <td><%= itemfriend.Itemservice %></td>
    <td><%= link_to 'Show', itemfriend %></td>
    <td><%= link_to 'Edit', edit_itemfriend_path(itemfriend) %></td>
    <td><%= link_to 'Destroy', itemfriend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Add Friends', new_itemfriend_path %> | 
<%= link_to 'Edit', edit_itemservice_path(@itemservice) %> |
<%= link_to 'Back', itemservices_path %>