eShopVite/config/routes.rb
EShopVite::Application.routes.draw do

  resources :itemfriends

  root :to => "itemservices#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
     get "sign_in", :to => "devise/sessions#new"
     get "/", :to => "devise/sessions#new"
     get "sign_out", :to => "devise/sessions#destroy"
     get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end



  resources :itemservices

   resources :itemservices do
       resources :itemfriends
   end

  match 'itemfriends/new/:itemservice_id'          => 'itemfriends#new'
 #  match 'itemfriends/new/:itemservice_id/:emailid' => 'itemfriends#new'

end

eShopVite/app/models/itemfriend.rb
class Itemfriend < ActiveRecord::Base
  belongs_to :Itemservice
  attr_accessible :itemservice_id, :amount, :comments, :interested, :qty, :emailid

end

eShopVite/app/controllers/itemfriends_controller.rb
class ItemfriendsController < ApplicationController
  # GET /itemfriends
  # GET /itemfriends.json
  def index
    @itemfriends = Itemfriend.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @itemfriends }
    end
  end

  # GET /itemfriends/1
  # GET /itemfriends/1.json
  def show
    @itemfriend = Itemfriend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @itemfriend }
    end
  end

  # GET /itemfriends/new
  # GET /itemfriends/new.json
  def new
    @itemfriend = Itemfriend.new
    
    @itemservice = Itemservice.find(:first, :conditions => ["friendslistid = ?", (params[:itemservice_id])])
    @itemfriend.emailid = params[:emailid]
    @itemfriend.itemservice_id = @itemservice.id   


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @itemfriend }
    end
  end

  # GET /itemfriends/1/edit
  def edit
    @itemfriend = Itemfriend.find(params[:id])
  end

  # POST /itemfriends
  # POST /itemfriends.json
  def create
    @itemfriend = Itemfriend.new(params[:itemfriend])

    respond_to do |format|
      if @itemfriend.save
        format.html { redirect_to @itemfriend, notice: 'Itemfriend was successfully created.' }
        format.json { render json: @itemfriend, status: :created, location: @itemfriend }
      else
        format.html { render action: "new" }
        format.json { render json: @itemfriend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /itemfriends/1
  # PUT /itemfriends/1.json
  def update
    @itemfriend = Itemfriend.find(params[:id])

    respond_to do |format|
      if @itemfriend.update_attributes(params[:itemfriend])
        format.html { redirect_to @itemfriend, notice: 'Itemfriend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @itemfriend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itemfriends/1
  # DELETE /itemfriends/1.json
  def destroy
    @itemfriend = Itemfriend.find(params[:id])
    @itemfriend.destroy

    respond_to do |format|
      format.html { redirect_to itemfriends_url }
      format.json { head :no_content }
    end
  end
end

eShopVite/app/helpers/itemfriends_helper.rb
module ItemfriendsHelper
end

eShopVite/app/views/itemfriends/_form.html.erb
<%= form_for(@itemfriend) do |f| %>
  <% if @itemfriend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@itemfriend.errors.count, "error") %> prohibited this itemfriend from being saved:</h2>

      <ul>
      <% @itemfriend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <div class="field">
    <%= f.label :emailid %><br />
    <%= f.text_field  :emailid %>
  </div>

 <div class="field">
    <%= f.label :interested %>
    <%= f.check_box :interested %>
  </div>

  <div class="field">
    <%= f.label :qty %><br />
    <%= f.number_field :qty %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<%= f.hidden_field :itemservice_id %>
<% end %>

eShopVite/app/views/itemfriends/_shows.html.erb
<h1>Listing itemfriends</h1>

<table>
  <tr>
    <th>Interested</th>
    <th>Qty</th>
    <th>Amount</th>
    <th>Comments</th>
    <th>Itemservice</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @itemfriends.each do |itemfriend| %>
  <tr>
    
<td><%= if itemfriend.interested?   "Yes" else "No" end %></td>
    <td><%= itemfriend.qty %></td>
    <td><%= itemfriend.amount %></td>
    <td><%= itemfriend.comments %></td>
    <td><%= itemfriend.Itemservice %></td>
    <td><%= link_to 'Show', itemfriend %></td>
    <td><%= link_to 'Edit', edit_itemfriend_path(itemfriend) %></td>
    <td><%= link_to 'Destroy', itemfriend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Itemfriend', new_itemfriend_path %>

eShopVite/app/views/itemfriends/edit.html.erb
<h1>Editing itemfriend</h1>

<%= render 'form' %>

<%= link_to 'Show', @itemfriend %> |
<%= link_to 'Back', itemfriends_path %>

eShopVite/app/views/itemfriends/index.html.erb
<h1>Listing itemfriends</h1>

<table>
  <tr>
    <th>Interested</th>
    <th>Qty</th>
    <th>Amount</th>
    <th>Comments</th>
    <th>Itemservice</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @itemfriends.each do |itemfriend| %>
  <tr>
    <td><%= itemfriend.interested %></td>
    <td><%= itemfriend.qty %></td>
    <td><%= itemfriend.amount %></td>
    <td><%= itemfriend.comments %></td>
    <td><%= itemfriend.Itemservice %></td>
    <td><%= link_to 'Show', itemfriend %></td>
    <td><%= link_to 'Edit', edit_itemfriend_path(itemfriend) %></td>
    <td><%= link_to 'Destroy', itemfriend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Itemfriend', new_itemfriend_path %>

eShopVite/app/views/itemfriends/new.html.erb
<h2>Items/Services Interest </h2>

<%= render 'form' %>

<%= link_to 'Back', itemfriends_path %>

eShopVite/app/views/itemfriends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Interested:</b>
  <%= @itemfriend.interested %>
</p>

<p>
  <b>Qty:</b>
  <%= @itemfriend.qty %>
</p>

<p>
  <b>Amount:</b>
  <%= @itemfriend.amount %>
</p>

<p>
  <b>Comments:</b>
  <%= @itemfriend.comments %>
</p>

<%= link_to 'Edit', edit_itemfriend_path(@itemfriend) %> |
<%= link_to 'Back', itemfriends_path %>