authExample/config/routes.rb
AuthExample::Application.routes.draw do
  get "home/index"

  root :to => "home#index"
   
  devise_scope :user do
      get '/users/sign_in' =>  "devise/sessions#new"
  end

 devise_scope :user do
  delete "/logout" => "devise/sessions#destroy"
end
  resources :linkedin
  resources :linkedin#callback
  resources :friendslists
  devise_scope :user do
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"} 

end

authExample/app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

authExample/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :confirmable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :provider, :uid, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
  end
  user
end


end

authExample/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

authExample/app/controllers/friendslists_controller.rb
class FriendslistsController < ApplicationController
  # GET /friendslists
  # GET /friendslists.json
  def index
    @friendslists = Friendslist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friendslists }
    end
  end

  # GET /friendslists/1
  # GET /friendslists/1.json
  def show
#    @friendslist = Friendslist.find(params[:id])

   

   @friendslist = Array.new 
  # if session["fb_access_token"].present?

    @user = User.find(params[:id])

    graph = Koala::Facebook::GraphAPI.new(session["fb_access_token"])
    @friendslist = graph.get_connections('me', "friends",:fields =>"name,gender,email,relationship_status")
    
#    graph.put_connections("me", "notes", :subject => "eShopVite", :message => "Message from eShopVite to register")


 # if current_user
 #     graph = Koala::Facebook::GraphAPI.new(@token)
 #     @friendslist = graph.get_connections("me", "friends")
 #  end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friendslist }
    end
  end

  # GET /friendslists/new
  # GET /friendslists/new.json
  def new
    @friendslist = Friendslist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friendslist }
    end
  end

  # GET /friendslists/1/edit
  def edit
    @friendslist = Friendslist.find(params[:id])
  end

  # POST /friendslists
  # POST /friendslists.json
  def create
    @friendslist = Friendslist.new(params[:friendslist])

    respond_to do |format|
      if @friendslist.save
        format.html { redirect_to @friendslist, notice: 'Friendslist was successfully created.' }
        format.json { render json: @friendslist, status: :created, location: @friendslist }
      else
        format.html { render action: "new" }
        format.json { render json: @friendslist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /friendslists/1
  # PUT /friendslists/1.json
  def update
    @friendslist = Friendslist.find(params[:id])

    respond_to do |format|
      if @friendslist.update_attributes(params[:friendslist])
        format.html { redirect_to @friendslist, notice: 'Friendslist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @friendslist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendslists/1
  # DELETE /friendslists/1.json
  def destroy
    @friendslist = Friendslist.find(params[:id])
    @friendslist.destroy

    respond_to do |format|
      format.html { redirect_to friendslists_url }
      format.json { head :no_content }
    end
  end
end

authExample/app/controllers/home_controller.rb
class HomeController < ApplicationController

before_filter :authenticate_user!
  def index
  end
end

authExample/app/controllers/linkedin_controller.rb
require 'linkedin'

class LinkedinController < ApplicationController

    
  def index 
   client = LinkedIn::Client.new("2nmn1vbprfxz", "IpyZTDybPZJ87mzH", LINKEDIN_CONFIGURATION )
    request_token = client.request_token(:oauth_callback => 
                                      "http://localhost:3001/linkedin/callback")
    session[:rtoken] = request_token.token
    session[:rsecret] = request_token.secret

    redirect_to client.request_token.authorize_url

  end

  def show

    client = LinkedIn::Client.new("2nmn1vbprfxz", "IpyZTDybPZJ87mzH", LINKEDIN_CONFIGURATION )
    if session[:atoken].nil?
      pin = params[:oauth_verifier]
      atoken, asecret = client.authorize_from_request(session[:rtoken], session[:rsecret], pin)
      session[:atoken] = atoken
      session[:asecret] = asecret
    else
      client.authorize_from_access(session[:atoken], session[:asecret])
    end
#    @profile = client.profile
     @profile = client.profile(:fields => %w(skills)) 
   #@connections = client.connections
    render 'friendslists/show'
  end
end

authExample/app/helpers/application_helper.rb
module ApplicationHelper
end

authExample/app/helpers/friendslists_helper.rb
module FriendslistsHelper
end

authExample/app/helpers/home_helper.rb
module HomeHelper
end

authExample/app/views/friendslists/_form.html.erb
<%= form_for(@friendslist) do |f| %>
  <% if @friendslist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendslist.errors.count, "error") %> prohibited this friendslist from being saved:</h2>

      <ul>
      <% @friendslist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field f['email'] %>
  </div>
  <div class="field">
    <%= f.label :include %><br />
    <%= f.check_box f['name'] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

authExample/app/views/friendslists/edit.html.erb
<h1>Editing friendslist</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendslist %> |
<%= link_to 'Back', friendslists_path %>

authExample/app/views/friendslists/index.html.erb
<h1>Listing friendslists</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Include</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friendslists.each do |friendslist| %>
  <tr>
    <td><%= friendslist.name %></td>
    <td><%= friendslist.include %></td>
    <td><%= link_to 'Show', friendslist %></td>
    <td><%= link_to 'Edit', edit_friendslist_path(friendslist) %></td>
    <td><%= link_to 'Destroy', friendslist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friendslist', new_friendslist_path %>

authExample/app/views/friendslists/new.html.erb
<h1>New friendslist</h1>

<%= render 'form' %>

<%= link_to 'Back', friendslists_path %>

authExample/app/views/friendslists/show.html.erb
<%= @profile %>

    <script src="http://connect.facebook.net/en_US/all.js"></script>
    <div id="fb-root"></div>
    <script>
      // assume we are already logged in
      FB.init({appId: '361676400593065', xfbml: true, cookie: true});

      FB.ui({
          method: 'send',
          name: 'People Argue Just to Win',
          link: 'http://www.nytimes.com/2011/06/15/arts/people-argue-just-to-win-scholars-assert.html',
          });
     </script>

authExample/app/views/home/index.html.erb
<h1>Home#index</h1>
<%= current_user.id  %><p>Find me in app/views/home/index.html.erb</p>

authExample/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>eShopVite Login</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<%= yield %>

<%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %>
</body>
</html>